#!/bin/bash
clear

PLAYLIST="%(extractor)s/playlists/%(playlist_title)s/%(uploader)s_%(channel_id)s - %(title)s [%(id)s].%(ext)s"
CHANNEL="%(extractor)s/%(uploader)s_%(channel_id)s/%(title)s [%(id)s].%(ext)s"
WEB="%(extractor)s/%(title)s [%(id)s].%(ext)s"

if [[ "$1" =~ ^.*youtu.*$ ]] || [[ "$1" =~ ^.*youtube.*$ ]]; then
    echo -e "Downloading video...\\n> URL: ${1}\\n"
    if [[ "$1" =~ .*/playlist.* ]] || [[ "$1" =~ .*list=.* ]]; then
        opt="$PLAYLIST"
        echo "Playlist detected"
    else
        opt="$CHANNEL"
        echo "Channel detected"
    fi
        yt-dlp --no-mtime --sponsorblock-remove "sponsor,intro,outro,selfpromo,preview" --embed-subs --sub-langs "all" -f "bv+ba/b" -o "/sdcard/Download/${opt}" "$1"
elif [[ "$1" =~ ^http.*$ ]]; then
    echo -e "Downloading video...\\n> URL: ${1}\\n"
    opt="$WEB"
    echo "Web address detected"
    yt-dlp --no-mtime --sponsorblock-remove "sponsor,intro,outro,selfpromo,preview" --embed-subs --sub-langs "all" -f "bv+ba/b" -o "/sdcard/Download/${opt}" "$1"
else
    echo "Error: No URL provided"
fi
